packages:
  - 'packages/*'
  - 'apps/*'
  - 'examples/*'
  - 'website'
allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': true
  core-js: false
  esbuild: true
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
